SELECT NOME_FORNECEDOR, PRECO FROM
(
	SELECT * FROM TEST.FORNECEDOR
	WHERE FORNECEDOR.CIDADE LIKE "VITORIA"
) AS FORNECEDOR
INNER JOIN TEST.FORNECIMENTO AS FORNECIMENTO
ON (FORNECIMENTO.CODIGO_CARRO = 'KOMBI' AND FORNECIMENTO.CODIGO_PECA = 'MOTOR')
INNER JOIN TEST.PECA AS PECA
ON PECA.CODIGO_PECA = 'MOTOR';
