DROP SCHEMA IF EXISTS TEST;
CREATE SCHEMA TEST;
USE TEST;

CREATE TABLE FORNECEDOR (
  `CODIGO_FORNECEDOR` INT NOT NULL AUTO_INCREMENT,
  `NOME_FORNECEDOR` VARCHAR(45) NOT NULL,
  `CIDADE` ENUM('VITORIA') NOT NULL,
  PRIMARY KEY (`CODIGO_FORNECEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TEST.FORNECEDOR (NOME_FORNECEDOR,CIDADE)
VALUES ('SUPERPECAS', 'VITORIA');

CREATE TABLE PECA (
  `CODIGO_PECA` VARCHAR(25) NOT NULL,
  `NOME_PECA` VARCHAR(50) NOT NULL,
  `PRECO` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`CODIGO_PECA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TEST.PECA (CODIGO_PECA, NOME_PECA, PRECO)
VALUES ('MOTOR', 'NOME PECA', '1000');

CREATE TABLE CARRO (
  `CODIGO_CARRO` varchar(25) NOT NULL,
  `NOME_CARRO` VARCHAR(25) NOT NULL,
  `TIPO` ENUM('TESTE'),
  PRIMARY KEY (`CODIGO_CARRO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TEST.CARRO (CODIGO_CARRO, NOME_CARRO, TIPO)
VALUES ('KOMBI', 'NOME_CARRO', 'TESTE');

CREATE TABLE FORNECIMENTO (
  `CODIGO_CARRO` varchar(25) NOT NULL,
  `CODIGO_PECA` VARCHAR(25) NOT NULL,
  `CODIGO_FORNECEDOR` INT NOT NULL,
  FOREIGN KEY (`CODIGO_CARRO`) REFERENCES CARRO(`CODIGO_CARRO`),
  FOREIGN KEY (`CODIGO_PECA`) REFERENCES PECA(`CODIGO_PECA`),
  FOREIGN KEY (`CODIGO_FORNECEDOR`) REFERENCES FORNECEDOR(`CODIGO_FORNECEDOR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO TEST.FORNECIMENTO (CODIGO_CARRO, CODIGO_PECA, CODIGO_FORNECEDOR)
VALUES ('KOMBI', 'MOTOR', 1);
